name: pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    name: Python unittest
    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: x64
      - run: python3 -m unittest -v
